### ISSUE TITLE
Important notes

### ISSUE THREAD

**Issue by isaactan001** [mokuteki225/nest-websockets-chat-boilerplate#4]
Thanks and appreciated the effort to come up with the repo.

Please correct me if I am wrong. I noticed the functions are called via `http` request instead of `ws` which does not serve the purpose of "websocket" therefore is totally a different thing than the title of this repo supposed to be.

If I am correct, I hope for the good of future learners, please remove the repo. Thanks again for your time reading this.

**Comment by vkondratiuk482** [comment]
Hey! The truth is that you don't need to handle all of your communication with the server via websockets. There are only some parts that need `ws`, in case of this project this part is [chat](https://github.com/mokuteki225/nest-websockets-chat-boilerplate/blob/master/src/chat/chat.gateway.ts), as soon as the user wants to join the chat - he establishes websocket connection. All of the following communication for the chat features is handled using websockets
